{
 "title": "demo2",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "step", "label": "step", "query": "15m, 30m,60m,2h,3h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "Base params", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sites / users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries t,\n    domain(page_url) as dom,\n    uniq(uid) as users\nFROM $table\nWHERE\n    $timeFilter and name = 'session' and uaparser_is_bot != 1\nGROUP BY t, dom\nORDER BY t, dom",
     "rawQuery": "SELECT     (intDiv(toUInt32(dateTime), 3600) * 3600) * 1000 t,     domain(page_url) as dom,     uniq(uid) as users FROM stats.events WHERE     date >= toDate(1542463982) AND dateTime >= toDateTime(1542463982) and name = 'session' and uaparser_is_bot != 1 GROUP BY t, dom ORDER BY t, dom",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Sites / sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries t,\n    domain(page_url) as dom,\n    count() as sessions\nFROM $table\nWHERE\n    $timeFilter and name = 'session' and uaparser_is_bot != 1\nGROUP BY t, dom\nORDER BY t, dom",
     "rawQuery": "SELECT     (intDiv(toUInt32(dateTime), 3600) * 3600) * 1000 t,     domain(page_url) as dom,     count() as sessions FROM stats.events WHERE     date >= toDate(1542463982) AND dateTime >= toDateTime(1542463982) and name = 'session' and uaparser_is_bot != 1 GROUP BY t, dom ORDER BY t, dom",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "    SELECT\n        $timeSeries t,\n        uniq(uid) as amount\n    FROM $table\n    WHERE\n        $timeFilter and name = 'session'\n    GROUP BY t\n    ORDER BY t",
     "rawQuery": "    SELECT         (intDiv(toUInt32(dateTime), 3600) * 3600) * 1000 t,         uniq(uid) as amount     FROM stats.events     WHERE         date >= toDate(1542463982) AND dateTime >= toDateTime(1542463982) and name = 'session'     GROUP BY t     ORDER BY t",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "    SELECT\n        $timeSeries t,\n        count() as amount\n    FROM $table\n    WHERE\n        $timeFilter and name = 'session'\n    GROUP BY t\n    ORDER BY t",
     "rawQuery": "    SELECT         (intDiv(toUInt32(dateTime), 3600) * 3600) * 1000 t,         count() as amount     FROM stats.events     WHERE         date >= toDate(1542463982) AND dateTime >= toDateTime(1542463982) and name = 'session'     GROUP BY t     ORDER BY t",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Pages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "    SELECT\n        $timeSeries t,\n        count() as amount\n    FROM $table\n    WHERE\n        $timeFilter and name = 'page'\n    GROUP BY t\n    ORDER BY t",
     "rawQuery": "    SELECT         (intDiv(toUInt32(dateTime), 3600) * 3600) * 1000 t,         count() as amount     FROM stats.events     WHERE         date >= toDate(1542463982) AND dateTime >= toDateTime(1542463982) and name = 'page'     GROUP BY t     ORDER BY t",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "MaxMind Countries",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    1,\n    groupArray((mmgeo_country_en, amount))\nFROM\n(\n    SELECT\n        mmgeo_country_en,\n        uniq(uid) AS amount\n    FROM $table\n    WHERE $timeFilter and name = 'session'\n    GROUP BY mmgeo_country_en\n    ORDER BY amount desc\n    LIMIT 5\n)",
     "rawQuery": "SELECT     1,     groupArray((mmgeo_country_en, amount)) FROM (     SELECT         mmgeo_country_en,         uniq(uid) AS amount     FROM stats.events     WHERE date >= toDate(1542463982) AND dateTime >= toDateTime(1542463982) and name = 'session'     GROUP BY mmgeo_country_en     ORDER BY amount desc     LIMIT 5 )",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Sources",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 9 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    1,\n    groupArray((sess_type,  Events))\nFROM\n(\n    SELECT\n        sess_type,\n        count() AS Events\n    FROM $table\n    WHERE $timeFilter AND name = 'session'\n    GROUP BY sess_type\n    ORDER BY Events desc\n    LIMIT 10\n)",
     "rawQuery": "SELECT     1,     groupArray((sess_type,  Events)) FROM (     SELECT         sess_type,         count() AS Events     FROM stats.events     WHERE date >= toDate(1542463982) AND dateTime >= toDateTime(1542463982) AND name = 'session'     GROUP BY sess_type     ORDER BY Events desc     LIMIT 10 )",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "New users/returning",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 9 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    1,\n    groupArray((userType,  Events))\nFROM\n(\n    SELECT\n        if(sess_num = 1,  'New',  'Returning') as userType,\n        count() AS Events\n    FROM $table\n    WHERE\n        $timeFilter\n        AND name = 'session'\n    GROUP BY userType\n    ORDER BY Events desc\n    LIMIT 10\n)",
     "rawQuery": "SELECT     1,     groupArray((userType,  Events)) FROM (     SELECT         if(sess_num = 1,  'New',  'Returning') as userType,         count() AS Events     FROM stats.events     WHERE         date >= toDate(1542463982) AND dateTime >= toDateTime(1542463982)         AND name = 'session'     GROUP BY userType     ORDER BY Events desc     LIMIT 10 )",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 9 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    1, /* fake timestamp value */\n    transform(uaparser_is_mob*3 + uaparser_is_pc*8, [8, 3], ['PC', 'Mobile'], 'Strange') as grp,\n    uniq(uid) AS amount\nFROM $table\nWHERE $timeFilter and name = 'session'\nGROUP BY grp\nORDER BY amount desc\nLIMIT 5\n\n",
     "rawQuery": "SELECT     1, /* fake timestamp value */     transform(uaparser_is_mob*3 + uaparser_is_pc*8, [8, 3], ['PC', 'Mobile'], 'Strange') as grp,     uniq(uid) AS amount FROM stats.events WHERE date >= toDate(1542463982) AND dateTime >= toDateTime(1542463982) and name = 'session' GROUP BY grp ORDER BY amount desc LIMIT 5  ",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Events amount",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "database": "stats",
       "dateColDataType": "date",
       "dateTimeColDataType": "dateTime",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "$columns(\n    name,\n    count() c)\nFROM $table",
       "rawQuery": "SELECT t, groupArray((name, c)) as groupArr FROM ( SELECT (intDiv(toUInt32(dateTime), 3600) * 3600) * 1000 as t, name, count() c FROM stats.activity WHERE date >= toDate(1542252029) AND dateTime >= toDateTime(1542252029) GROUP BY t, name  ORDER BY t, name) GROUP BY t ORDER BY t",
       "round": "0s",
       "table": "activity"
      },
      {
       "database": "stats",
       "dateColDataType": "date",
       "dateTimeColDataType": "dateTime",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "$columns(\n    name,\n    count() c)\nFROM $table",
       "rawQuery": "SELECT t, groupArray((name, c)) as groupArr FROM ( SELECT (intDiv(toUInt32(dateTime), 3600) * 3600) * 1000 as t, name, count() c FROM stats.events WHERE date >= toDate(1542252029) AND dateTime >= toDateTime(1542252029) GROUP BY t, name  ORDER BY t, name) GROUP BY t ORDER BY t",
       "round": "0s",
       "table": "events"
      }
     ]
    },
    {
     "title": "Events / Users",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "database": "stats",
       "dateColDataType": "date",
       "dateTimeColDataType": "dateTime",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "$columns(\n    name,\n    count()/uniq(uid) c)\nFROM $table",
       "rawQuery": "SELECT t, groupArray((name, c)) as groupArr FROM ( SELECT (intDiv(toUInt32(dateTime), 3600) * 3600) * 1000 as t, name, count() / uniq(uid) c FROM stats.activity WHERE date >= toDate(1542252029) AND dateTime >= toDateTime(1542252029) GROUP BY t, name  ORDER BY t, name) GROUP BY t ORDER BY t",
       "round": "0s",
       "table": "activity"
      },
      {
       "database": "stats",
       "dateColDataType": "date",
       "dateTimeColDataType": "dateTime",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "$columns(\n    name,\n    count()/uniq(uid) c)\nFROM $table",
       "rawQuery": "SELECT t, groupArray((name, c)) as groupArr FROM ( SELECT (intDiv(toUInt32(dateTime), 3600) * 3600) * 1000 as t, name, count() / uniq(uid) c FROM stats.events WHERE date >= toDate(1542252029) AND dateTime >= toDateTime(1542252029) GROUP BY t, name  ORDER BY t, name) GROUP BY t ORDER BY t",
       "round": "0s",
       "table": "events"
      }
     ]
    }
   ]
  },
  { "title": "Sources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Domains, dates uniq users",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    domain(page_url) as dom,\n    uniq(uid) as users,\n    countIf(name = 'session') as sessions,\n    uniq(uid+sess_num) as sessions2,\n    count() as evends_wo_act\nFROM $table\nWHERE $timeFilter\nGROUP BY dom\nORDER BY dom",
     "rawQuery": "SELECT     domain(page_url) as dom,     uniq(uid) as users,     countIf(name = 'session') as sessions,     uniq(uid+sess_num) as sessions2,     count() as evends_wo_act FROM stats.events WHERE date >= toDate(1542463982) AND dateTime >= toDateTime(1542463982) GROUP BY dom ORDER BY dom",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Organic and Social",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    domain(page_url) as dom,\n    sess_type as stype,\n    sess_engine as engine,\n    path(page_url) as ppath,\n    uniq(uid) as users,\n    count() as sessions\nFROM $table\nWHERE $timeFilter and name = 'session' and (sess_type = 'organic' or sess_type == 'social')\nGROUP BY engine, dom, stype, ppath\nORDER BY users DESC",
     "rawQuery": "SELECT     domain(page_url) as dom,     sess_type as stype,     sess_engine as engine,     path(page_url) as ppath,     uniq(uid) as users,     count() as sessions FROM stats.events WHERE date >= toDate(1542463982) AND dateTime >= toDateTime(1542463982) and name = 'session' and (sess_type = 'organic' or sess_type == 'social') GROUP BY engine, dom, stype, ppath ORDER BY users DESC",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Campaigns",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    domain(page_url) as dom,\n    sess_marks_utm_source as utm_source,\n    sess_marks_utm_campaign as utm_campaing,\n    sess_marks_utm_medium as utm_medium,\n    uniq(uid) as users,\n    count() as sessions\nFROM $table\nWHERE $timeFilter and name = 'session' and sess_type = 'campaign'\nGROUP BY utm_source, utm_campaing, utm_medium, dom\nORDER BY users",
     "rawQuery": "SELECT     domain(page_url) as dom,     sess_marks_utm_source as utm_source,     sess_marks_utm_campaign as utm_campaing,     sess_marks_utm_medium as utm_medium,     uniq(uid) as users,     count() as sessions FROM stats.events WHERE date >= toDate(1542463982) AND dateTime >= toDateTime(1542463982) and name = 'session' and sess_type = 'campaign' GROUP BY utm_source, utm_campaing, utm_medium, dom ORDER BY users",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Referrers",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    domain(page_url) as dom,\n    sess_refhost as refhost,\n    uniq(uid) as users,\n    count() as sessions\nFROM $table\nWHERE $timeFilter and name = 'session' and sess_type = 'referral'\nGROUP BY sess_refhost, dom\nORDER BY users",
     "rawQuery": "SELECT     domain(page_url) as dom,     sess_refhost as refhost,     uniq(uid) as users,     count() as sessions FROM stats.events WHERE date >= toDate(1542463982) AND dateTime >= toDateTime(1542463982) and name = 'session' and sess_type = 'referral' GROUP BY sess_refhost, dom ORDER BY users",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  {
   "title": "Internal session",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    domain(page_url) as dom,\n    path(page_url) as start_path,\n    uniq(uid) as users,\n    count() as sessions\nFROM $table\nWHERE $timeFilter and name = 'session' and sess_type == 'internal'\nGROUP BY dom, start_path\nORDER BY users DESC",
     "rawQuery": "SELECT     domain(page_url) as dom,     path(page_url) as start_path,     uniq(uid) as users,     count() as sessions FROM stats.events WHERE date >= toDate(1542463982) AND dateTime >= toDateTime(1542463982) and name = 'session' and sess_type == 'internal' GROUP BY dom, start_path ORDER BY users DESC",
     "round": "0s",
     "table": "events"
    }
   ]
  },
  { "title": "Content", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Top pages",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "database": "stats",
     "dateColDataType": "date",
     "dateTimeColDataType": "dateTime",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    domain(page_url) as dom,\n    path(page_url) as page_path,\n    uniq(uid) as users,\n    count() as pageviews\nFROM $table\nWHERE $timeFilter and name = 'page' and (sess_type = 'organic' or sess_type == 'social')\nGROUP BY page_path, dom\nORDER BY pageviews DESC",
     "rawQuery": "SELECT     domain(page_url) as dom,     path(page_url) as page_path,     uniq(uid) as users,     count() as pageviews FROM stats.events WHERE date >= toDate(1542464020) AND dateTime >= toDateTime(1542464020) and name = 'page' and (sess_type = 'organic' or sess_type == 'social') GROUP BY page_path, dom ORDER BY pageviews DESC",
     "round": "0s",
     "table": "events"
    }
   ]
  }
 ]
}